spring:
  rabbitmq:
    host: rabbitmq
    port: 5672

  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password

server:
  port: 8082

notification:
  exchange: consultas.exchange
  queue: consultas.notifications
  routingKey: consulta.criada
